### ISSUE TITLE
[Refactor] 1주차 수요일 리뷰 반영

### ISSUE THREAD

**Issue by nanjeong** [KTH-96/issue-tracker#12]
### Description

- 1주차 수요일 리뷰를 반영한다.

### Tasks

- [ ] ts-loader -> babel-loader 변경
- [x] svgs/index.tsx -> svgs/index.ts 확장자 변경
- [x] reset.css 출처 주석에 남기기
- [x] webpack.config.js 출처 주석에 남기기
- [x] .eslintrc value 숫자 -> 영문 변경
- [x] 커밋 타입 구체화

**Comment by nanjeong** [comment]
예상 작업 시간: 1.5

**Comment by nanjeong** [comment]
- [ ]  ts-loader -> babel-loader 변경
외 작업 시간 : 1.2
