### ISSUE TITLE
이슈목록 - 다중 선택

### ISSUE THREAD

**Issue by nanjeong** [KTH-96/issue-tracker#27]
### Description

- 이슈 목록의 체크 박스를 클릭해 이슈를 선택할 수 있다.
- 이슈 목록 상단의 체크 박스를 클릭하면 현재 이슈 목록의 아이템을 모두 선택하게 된다.
- 이슈 목록 아이템의 체크 박스를 클릭하면 클릭한 아이템만 선택된다.

### Tasks
- [x] 이슈 목록 아이템의 체크 박스 클릭 
    - [x] 클릭한 아이템의 체크박스 선택됨 (선택된 상태면 선택 해제)
    - [x] 이슈 목록 상단의 체크박스 disabled로 변경
    - [x] 열린이슈/ 닫힌 이슈 탭 부분에 선택된 이슈 개수를 알려주는 텍스트 표시
    - [x] 이슈 목록 우측 상단 탭 상태 수정 탭으로 변경
- [x] 이슈 목록 상단의 체크 박스 클릭
    - [x] 이슈 목록의 아이템 모두 선택 (선택된 상태면 선택 해제)
- [x] 모든 이슈 목록 아이템의 선택이 해제되면 다시 원래 상태로 돌아감

**Comment by nanjeong** [comment]
예상 시간 : 2시간

**Comment by nanjeong** [comment]
소요 시간: 3시간 30분 (예상 시간 + 1시간 30분)

원인 분석
- mock data 사용 여부 고민
- 상단 체크박스 상태와 목록 아이템의 체크박스 상태 동기화 부분에서 헤맴.

**Comment by nanjeong** [comment]
### 추가 Tasks

- [x] 목록 아이템에 mock data 적용

예상 시간: 1시간 30분

**Comment by nanjeong** [comment]
소요 시간: 1시간 15분 (예상 시간 - 15분)

- 일단 목록 아이템에 mock data 적용하는 것만 신경 씀
- 현재 이슈 목록이 열린 이슈인지 닫힌 이슈인지는 아직 고려하지 않음
