### ISSUE TITLE
이슈 목록 - react query로 데이터 가져오기 

### ISSUE THREAD

**Issue by nanjeong** [KTH-96/issue-tracker#42]
### Description
- 이슈 목록 데이터를 react query를 사용해서 가져온다.

### Tasks

- [x] 이슈 아이템 열림/닫힘에 따라 다른 아이콘 나오도록 수정
- [x] 빈 데이터에 대한 처리 변경 (빈 배열, 빈 문자열이 아니라 null로 되어 있음)
- [x] reducer action payload가 없는 경우 처리
- [x] 데이터 가져오는 부분 react query의 useQuery로 변경

**Comment by nanjeong** [comment]
예상 시간 : 4시간

**Comment by nanjeong** [comment]
소요 시간: 2시간 반

**Comment by nanjeong** [comment]
- 추가 작업: 라우팅에 dynamic import, lazy loading 적용
