### ISSUE TITLE
이슈 목록 - 체크한 이슈 아이템 상태 변경

### ISSUE THREAD

**Issue by nanjeong** [KTH-96/issue-tracker#50]
### Description
이슈 목록의 선택한 아이템의 상태를 변경한다.

### Tasks

- [x] checkReducer action type 변경
- [x] 상태 수정 탭 추가 
- [x] 상태 수정 탭을 클릭하면 상태 수정 드롭 다운이 나타남
- [ ] 이슈 열기/닫기 클릭, 상태 변경 요청
- [ ] 이슈 목록 업데이트

**Comment by nanjeong** [comment]
예상 시간: 4시간
