### ISSUE TITLE
이슈 목록 - 이슈 목록에서 분기하는 페이지 라우터 설정

### ISSUE THREAD

**Issue by nanjeong** [KTH-96/issue-tracker#7]
### Description

- 이슈 목록에서 분기하는 라우터 설정하기

### Tasks
- [x] 이슈 제목 버튼을 클릭하면 해당 이슈에 대한 상세화면으로 이동한다. 
  - 일단은 '/detail'로 분기, 추후 이슈 번호로 관리 '/detail/이슈번호'
- [x] 레이블 탭을 누르면 레이블 목록 페이지로 이동한다.
- [x] 마일스톤 탭을 누르면 마일스톤 목록 페이지로 이동한다.
- [x] 이슈작성 버튼을 클릭하면 이슈작성 페이지로 이동한다.
